package com.carettafriends.content

/**
 * UI string catalog for the whole interface (EN/RU/TR). Screens read the current bundle via
 * [appStrings]`(state.profile.language)` — the language is set in Profile → Language and persists.
 * Guide article bodies stay in [GuideContent]; this is the app chrome.
 */
data class AppStrings(
    // bottom navigation
    val navMap: String,
    val navBeaches: String,
    val navLearn: String,
    val navProfile: String,
    // common actions
    val save: String,
    val cancel: String,
    val close: String,
    val done: String,
    val change: String,
    // map filters + chrome
    val filterAll: String,
    val filterNests: String,
    val filterHatching: String,
    val filterTrash: String,
    val startPatrol: String,
    val stopPatrol: String,
    val noPatrolYet: String,
    // beaches
    val beaches: String,
    val nearYou: String,
    val allBeaches: String,
    val showBeaches: String,
    val nearMeAuto: String,
    val findingBeaches: String,
    // profile
    val profile: String,
    val saveAccount: String,
    val saveAccountSub: String,
    val signedIn: String,
    val hatchlingsReached: String,
    val dayStreak: String,
    val walked: String,
    val patrols: String,
    val community: String,
    val myBeach: String,
    val freeVolunteer: String,
    val patrolClosest: String,
    val yourHomeBeach: String,
    val homeBeach: String,
    val patrolled: String,
    val badges: String,
    val noBadges: String,
    val myPhotos: String,
    val trends: String,
    val language: String,
    val yourName: String,
    val displayName: String,
    // email auth
    val signIn: String,
    val email: String,
    val passwordHint: String,
    val haveAccount: String,
    val newHere: String,
    val saveAccountBody: String,
    val welcomeBack: String,
    // beach card metrics (word after a number) + labels
    val nestsWord: String,
    val activeWord: String,
    val soonWord: String,
    val hatchedWord: String,
    val beachWord: String,
    val protectedWord: String,
    // nest detail
    val watch: String,
    val watching: String,
    val foundWord: String,
    val hatchWindow: String,
    val predictedModel: String,
    val exFullSun: String,
    val exPartial: String,
    val exShade: String,
    val exUnknown: String,
    val airWord: String,
    val rain7d: String,
    val timeline: String,
    val addUpdate: String,
    val comment: String,
    val excavation: String,
    val excavationLockedSub: String,
    val needsConfirm: String,
    val condition: String,
    val dateWord: String,
    val whatObserved: String,
    val writeComment: String,
    val condOk: String,
    val condHatching: String,
    val condHatched: String,
    val condDisturbed: String,
    val condPredated: String,
    val condWashed: String,
    val nestFoundDate: String,
    val backDateHelp: String,
    val today: String,
    val yesterday: String,
    val daysAgo: String, // "%d" placeholder
    // add-nest form
    val newMarker: String,
    val whatFound: String,
    val segNest: String,
    val segLandmark: String,
    val segTrash: String,
    val nestOrFalse: String,
    val segFalseCrawl: String,
    val photo: String,
    val retake: String,
    val cameraBtn: String,
    val gallery: String,
    val photoAdded: String,
    val location: String,
    val fromExif: String,
    val noGpsInPhoto: String,
    val confirmed: String,
    val unconfirmed: String,
    val detectedFrom: String,
    val changePlain: String,
    val noLocationYet: String,
    val notRecognizedBeach: String,
    val protection: String,
    val protNone: String,
    val protReed: String,
    val protCage: String,
    val protectionHelp: String,
    val optionalSun: String,
    val segSun: String,
    val segPartial: String,
    val segShade: String,
    val visibility: String,
    val visPublic: String,
    val visPrivate: String,
    val saveNest: String,
    val saveFalseCrawl: String,
)

private val EN = AppStrings(
    navMap = "Map", navBeaches = "Beaches", navLearn = "Learn", navProfile = "Profile",
    save = "Save", cancel = "Cancel", close = "Close", done = "Done", change = "Change ›",
    filterAll = "All", filterNests = "🥚 Nests", filterHatching = "● Hatching soon", filterTrash = "🧺 Trash",
    startPatrol = "● Start patrol", stopPatrol = "■ Stop patrol", noPatrolYet = "No patrol yet today",
    beaches = "Beaches", nearYou = "Near you", allBeaches = "All beaches", showBeaches = "Show beaches",
    nearMeAuto = "📍 Near me (auto)", findingBeaches = "Finding beaches near you…\nThey load automatically from the map.",
    profile = "Profile", saveAccount = "Save your account",
    saveAccountSub = "Add an email so your work isn't lost if you change phone.",
    signedIn = "Signed in", hatchlingsReached = "hatchlings reached the sea 🌊",
    dayStreak = "day streak", walked = "walked", patrols = "patrols", community = "Community",
    myBeach = "My beach", freeVolunteer = "🌊 Free volunteer", patrolClosest = "Patrol wherever's closest",
    yourHomeBeach = "Your home beach", homeBeach = "Home beach", patrolled = "Patrolled",
    badges = "Badges", noBadges = "No badges yet — patrol & log nests to earn your first 🐢",
    myPhotos = "My photos", trends = "📊  Trends & charts", language = "🌐  Language",
    yourName = "Your name", displayName = "Display name",
    signIn = "Sign in", email = "Email", passwordHint = "Password (6+ chars)",
    haveAccount = "Already have an account? Sign in", newHere = "New here? Create an account",
    saveAccountBody = "Add an email + password so your work syncs and isn't lost if you change phone.",
    welcomeBack = "Welcome back — sign in to load your nests & impact.",
    nestsWord = "nests", activeWord = "active", soonWord = "soon", hatchedWord = "hatched",
    beachWord = "Beach", protectedWord = "protected",
    watch = "🔔 Watch", watching = "🔔 Watching", foundWord = "found", hatchWindow = "Hatch window",
    predictedModel = "predicted · regional model (Anamur 28.9°C)",
    exFullSun = "full sun", exPartial = "partial", exShade = "shade", exUnknown = "exposure ?",
    airWord = "air", rain7d = "rain 7d", timeline = "Timeline · updates & comments",
    addUpdate = "＋ Add update", comment = "💬 Comment", excavation = "⛏️ Excavation",
    excavationLockedSub = "Done by experienced volunteers & beach leaders — ask your beach leader.",
    needsConfirm = "⚠️  Needs a photo / precise location — tap to confirm",
    condition = "Condition", dateWord = "Date", whatObserved = "What did you observe?", writeComment = "Write a comment…",
    condOk = "OK", condHatching = "Hatching", condHatched = "Hatched", condDisturbed = "Disturbed",
    condPredated = "Predated", condWashed = "Washed over",
    nestFoundDate = "Nest found date",
    backDateHelp = "Word-of-mouth it was found earlier but the photo arrived now? Set the real day — up to a month back. The incubation day & hatch forecast recompute automatically.",
    today = "today", yesterday = "yesterday", daysAgo = "%d days ago",
    newMarker = "New marker", whatFound = "What did you find?",
    segNest = "🥚 Nest", segLandmark = "🚩 Landmark", segTrash = "🧺 Trash",
    nestOrFalse = "Nest or false crawl?", segFalseCrawl = "🌀 False crawl",
    photo = "Photo", retake = "📷 Retake", cameraBtn = "📷 Camera", gallery = "🖼️ Gallery", photoAdded = "Photo added",
    location = "Location", fromExif = "From photo · EXIF", noGpsInPhoto = "No GPS in photo — set to the beach",
    confirmed = "Confirmed ✓", unconfirmed = "Unconfirmed", detectedFrom = "Detected from your location",
    changePlain = "Change", noLocationYet = "No location yet — take a photo on-site or pick the beach.",
    notRecognizedBeach = "🌊 Not recognized as a known nesting beach — pick the right one.",
    protection = "Protection", protNone = "None", protReed = "🌾 Reed", protCage = "🛡️ Cage",
    protectionHelp = "Reed = stakes + reed fence + tape + sign. Cage = metal cage (stronger, but scarce & heavy).",
    optionalSun = "Optional: sun exposure", segSun = "☀️ Sun", segPartial = "⛅ Partial", segShade = "🌴 Shade",
    visibility = "Visibility", visPublic = "🌍 Public", visPrivate = "🔒 Private",
    saveNest = "Save nest 🐢", saveFalseCrawl = "Save false crawl 🌀",
)

private val RU = AppStrings(
    navMap = "Карта", navBeaches = "Пляжи", navLearn = "Гайд", navProfile = "Профиль",
    save = "Сохранить", cancel = "Отмена", close = "Закрыть", done = "Готово", change = "Изменить ›",
    filterAll = "Все", filterNests = "🥚 Гнёзда", filterHatching = "● Скоро вылупятся", filterTrash = "🧺 Мусор",
    startPatrol = "● Начать патруль", stopPatrol = "■ Стоп патруль", noPatrolYet = "Патруля сегодня ещё нет",
    beaches = "Пляжи", nearYou = "Рядом с вами", allBeaches = "Все пляжи", showBeaches = "Показывать пляжи",
    nearMeAuto = "📍 Рядом (авто)", findingBeaches = "Ищем пляжи рядом…\nОни подгружаются с карты автоматически.",
    profile = "Профиль", saveAccount = "Сохранить аккаунт",
    saveAccountSub = "Добавь почту, чтобы данные не потерялись при смене телефона.",
    signedIn = "Вы вошли", hatchlingsReached = "черепашат добрались до моря 🌊",
    dayStreak = "дней подряд", walked = "пройдено", patrols = "патрулей", community = "Сообщество",
    myBeach = "Мой пляж", freeVolunteer = "🌊 Свободный волонтёр", patrolClosest = "Патрулирую где ближе",
    yourHomeBeach = "Твой домашний пляж", homeBeach = "Домашний пляж", patrolled = "Был на пляжах",
    badges = "Бейджи", noBadges = "Бейджей пока нет — патрулируй и отмечай гнёзда 🐢",
    myPhotos = "Мои фото", trends = "📊  Графики и тренды", language = "🌐  Язык",
    yourName = "Твоё имя", displayName = "Отображаемое имя",
    signIn = "Войти", email = "Почта", passwordHint = "Пароль (6+ символов)",
    haveAccount = "Уже есть аккаунт? Войти", newHere = "Впервые? Создать аккаунт",
    saveAccountBody = "Добавь почту и пароль — данные синхронизируются и не потеряются при смене телефона.",
    welcomeBack = "С возвращением — войди, чтобы загрузить свои гнёзда и вклад.",
    nestsWord = "гнёзд", activeWord = "активн.", soonWord = "скоро", hatchedWord = "вылупились",
    beachWord = "Пляж", protectedWord = "под охраной",
    watch = "🔔 Следить", watching = "🔔 Слежу", foundWord = "найдено", hatchWindow = "Окно вылупления",
    predictedModel = "прогноз · региональная модель (Анамур 28.9°C)",
    exFullSun = "солнце", exPartial = "полутень", exShade = "тень", exUnknown = "освещённость ?",
    airWord = "возд.", rain7d = "дождь 7д", timeline = "Лента · апдейты и комменты",
    addUpdate = "＋ Апдейт", comment = "💬 Коммент", excavation = "⛏️ Вскрытие",
    excavationLockedSub = "Делают опытные волонтёры и лидеры пляжа — спроси своего лидера.",
    needsConfirm = "⚠️  Нужно фото / точная точка — нажми, чтобы подтвердить",
    condition = "Состояние", dateWord = "Дата", whatObserved = "Что заметил?", writeComment = "Напиши комментарий…",
    condOk = "ОК", condHatching = "Вылупляются", condHatched = "Вылупились", condDisturbed = "Потревожено",
    condPredated = "Хищник", condWashed = "Смыло",
    nestFoundDate = "Дата находки гнезда",
    backDateHelp = "Со слов нашли раньше, а фото дошло сейчас? Поставь реальный день — до месяца назад. День инкубации и прогноз вылупления пересчитаются автоматически.",
    today = "сегодня", yesterday = "вчера", daysAgo = "%d дн. назад",
    newMarker = "Новая метка", whatFound = "Что ты нашёл?",
    segNest = "🥚 Гнездо", segLandmark = "🚩 Ориентир", segTrash = "🧺 Мусор",
    nestOrFalse = "Гнездо или ложный выход?", segFalseCrawl = "🌀 Ложный выход",
    photo = "Фото", retake = "📷 Переснять", cameraBtn = "📷 Камера", gallery = "🖼️ Галерея", photoAdded = "Фото добавлено",
    location = "Локация", fromExif = "Из фото · EXIF", noGpsInPhoto = "В фото нет GPS — привязано к пляжу",
    confirmed = "Подтверждено ✓", unconfirmed = "Не подтверждено", detectedFrom = "Определено по локации",
    changePlain = "Изменить", noLocationYet = "Локации пока нет — сделай фото на месте или выбери пляж.",
    notRecognizedBeach = "🌊 Не распознан как известный пляж — выбери нужный.",
    protection = "Защита", protNone = "Нет", protReed = "🌾 Тростник", protCage = "🛡️ Клетка",
    protectionHelp = "Тростник = колышки + тростниковый забор + лента + табличка. Клетка = металлическая (крепче, но редкая и тяжёлая).",
    optionalSun = "Опционально: освещённость", segSun = "☀️ Солнце", segPartial = "⛅ Полутень", segShade = "🌴 Тень",
    visibility = "Видимость", visPublic = "🌍 Публично", visPrivate = "🔒 Приватно",
    saveNest = "Сохранить гнездо 🐢", saveFalseCrawl = "Сохранить ложный выход 🌀",
)

private val TR = AppStrings(
    navMap = "Harita", navBeaches = "Plajlar", navLearn = "Rehber", navProfile = "Profil",
    save = "Kaydet", cancel = "İptal", close = "Kapat", done = "Tamam", change = "Değiştir ›",
    filterAll = "Hepsi", filterNests = "🥚 Yuvalar", filterHatching = "● Yakında çıkacak", filterTrash = "🧺 Çöp",
    startPatrol = "● Devriyeye başla", stopPatrol = "■ Devriyeyi bitir", noPatrolYet = "Bugün henüz devriye yok",
    beaches = "Plajlar", nearYou = "Yakınında", allBeaches = "Tüm plajlar", showBeaches = "Plajları göster",
    nearMeAuto = "📍 Yakınım (oto)", findingBeaches = "Yakındaki plajlar aranıyor…\nHaritadan otomatik yüklenir.",
    profile = "Profil", saveAccount = "Hesabını kaydet",
    saveAccountSub = "Telefon değişince kaybolmaması için bir e-posta ekle.",
    signedIn = "Giriş yapıldı", hatchlingsReached = "yavru denize ulaştı 🌊",
    dayStreak = "gün seri", walked = "yürüdün", patrols = "devriye", community = "Topluluk",
    myBeach = "Plajım", freeVolunteer = "🌊 Serbest gönüllü", patrolClosest = "En yakın neresiyse orada",
    yourHomeBeach = "Ana plajın", homeBeach = "Ana plaj", patrolled = "Gezdiğin plajlar",
    badges = "Rozetler", noBadges = "Henüz rozet yok — devriye gez ve yuva kaydet 🐢",
    myPhotos = "Fotoğraflarım", trends = "📊  Grafikler ve eğilimler", language = "🌐  Dil",
    yourName = "Adın", displayName = "Görünen ad",
    signIn = "Giriş yap", email = "E-posta", passwordHint = "Şifre (6+ karakter)",
    haveAccount = "Hesabın var mı? Giriş yap", newHere = "Yeni misin? Hesap oluştur",
    saveAccountBody = "E-posta + şifre ekle — verilerin senkronize olur, telefon değişince kaybolmaz.",
    welcomeBack = "Tekrar hoş geldin — yuvalarını ve katkını yüklemek için giriş yap.",
    nestsWord = "yuva", activeWord = "aktif", soonWord = "yakında", hatchedWord = "çıktı",
    beachWord = "Plaj", protectedWord = "korunan",
    watch = "🔔 Takip et", watching = "🔔 Takipte", foundWord = "bulundu", hatchWindow = "Çıkış aralığı",
    predictedModel = "tahmin · bölgesel model (Anamur 28.9°C)",
    exFullSun = "tam güneş", exPartial = "yarı gölge", exShade = "gölge", exUnknown = "ışık ?",
    airWord = "hava", rain7d = "yağmur 7g", timeline = "Zaman çizelgesi · güncelleme & yorum",
    addUpdate = "＋ Güncelle", comment = "💬 Yorum", excavation = "⛏️ Kazı",
    excavationLockedSub = "Deneyimli gönüllüler ve plaj liderleri yapar — liderine sor.",
    needsConfirm = "⚠️  Fotoğraf / kesin konum gerekli — onaylamak için dokun",
    condition = "Durum", dateWord = "Tarih", whatObserved = "Ne gözlemledin?", writeComment = "Bir yorum yaz…",
    condOk = "OK", condHatching = "Çıkıyor", condHatched = "Çıktı", condDisturbed = "Rahatsız",
    condPredated = "Avlanmış", condWashed = "Su bastı",
    nestFoundDate = "Yuva buluş tarihi",
    backDateHelp = "Söylentiye göre daha önce bulundu ama fotoğraf şimdi mi geldi? Gerçek günü ayarla — bir aya kadar. İnkübasyon günü ve çıkış tahmini otomatik güncellenir.",
    today = "bugün", yesterday = "dün", daysAgo = "%d gün önce",
    newMarker = "Yeni işaret", whatFound = "Ne buldun?",
    segNest = "🥚 Yuva", segLandmark = "🚩 Nirengi", segTrash = "🧺 Çöp",
    nestOrFalse = "Yuva mı, boş çıkış mı?", segFalseCrawl = "🌀 Boş çıkış",
    photo = "Fotoğraf", retake = "📷 Tekrar çek", cameraBtn = "📷 Kamera", gallery = "🖼️ Galeri", photoAdded = "Fotoğraf eklendi",
    location = "Konum", fromExif = "Fotoğraftan · EXIF", noGpsInPhoto = "Fotoğrafta GPS yok — plaja bağlandı",
    confirmed = "Onaylandı ✓", unconfirmed = "Onaysız", detectedFrom = "Konumundan algılandı",
    changePlain = "Değiştir", noLocationYet = "Henüz konum yok — yerinde fotoğraf çek ya da plaj seç.",
    notRecognizedBeach = "🌊 Bilinen bir yuvalama plajı değil — doğrusunu seç.",
    protection = "Koruma", protNone = "Yok", protReed = "🌾 Kamış", protCage = "🛡️ Kafes",
    protectionHelp = "Kamış = kazık + kamış çit + bant + tabela. Kafes = metal kafes (daha güçlü ama nadir ve ağır).",
    optionalSun = "İsteğe bağlı: güneş", segSun = "☀️ Güneş", segPartial = "⛅ Yarı", segShade = "🌴 Gölge",
    visibility = "Görünürlük", visPublic = "🌍 Herkese açık", visPrivate = "🔒 Özel",
    saveNest = "Yuvayı kaydet 🐢", saveFalseCrawl = "Boş çıkışı kaydet 🌀",
)

/** The string bundle for [lang] ("ru" / "tr" / anything else → EN). */
fun appStrings(lang: String): AppStrings = when (lang.lowercase()) {
    "ru" -> RU
    "tr" -> TR
    else -> EN
}
