package com.carettafriends.content

/**
 * UI string catalog for the whole interface (EN/RU/TR). Screens read the current bundle via
 * [appStrings]`(state.profile.language)` — the language is set in Profile → Language and persists.
 * Guide article bodies stay in [GuideContent]; this is the app chrome.
 */
data class AppStrings(
    // bottom navigation
    val navMap: String,
    val navBeaches: String,
    val navLearn: String,
    val navProfile: String,
    // common actions
    val save: String,
    val cancel: String,
    val close: String,
    val done: String,
    val change: String,
    // map filters + chrome
    val filterAll: String,
    val filterNests: String,
    val filterHatching: String,
    val filterTrash: String,
    val startPatrol: String,
    val stopPatrol: String,
    val noPatrolYet: String,
    // beaches
    val beaches: String,
    val nearYou: String,
    val allBeaches: String,
    val showBeaches: String,
    val nearMeAuto: String,
    val findingBeaches: String,
    // profile
    val profile: String,
    val saveAccount: String,
    val saveAccountSub: String,
    val signedIn: String,
    val hatchlingsReached: String,
    val dayStreak: String,
    val walked: String,
    val patrols: String,
    val community: String,
    val myBeach: String,
    val freeVolunteer: String,
    val patrolClosest: String,
    val yourHomeBeach: String,
    val homeBeach: String,
    val patrolled: String,
    val badges: String,
    val noBadges: String,
    val myPhotos: String,
    val trends: String,
    val language: String,
    val yourName: String,
    val displayName: String,
    // email auth
    val signIn: String,
    val email: String,
    val passwordHint: String,
    val haveAccount: String,
    val newHere: String,
    val saveAccountBody: String,
    val welcomeBack: String,
    // beach card metrics (word after a number) + labels
    val nestsWord: String,
    val activeWord: String,
    val soonWord: String,
    val hatchedWord: String,
    val beachWord: String,
    val protectedBeachLabel: String,
    val protectedWord: String,
    // nest detail
    val watch: String,
    val watching: String,
    val foundWord: String,
    val foundByWord: String,
    val hatchWindow: String,
    val predictedModel: String,
    val exFullSun: String,
    val exPartial: String,
    val exShade: String,
    val exUnknown: String,
    val airWord: String,
    val rain7d: String,
    val timeline: String,
    val addUpdate: String,
    val comment: String,
    val excavation: String,
    val excavationLockedSub: String,
    val needsConfirm: String,
    val condition: String,
    val dateWord: String,
    val whatObserved: String,
    val writeComment: String,
    val condOk: String,
    val condHatching: String,
    val condHatched: String,
    val condDisturbed: String,
    val condPredated: String,
    val condWashed: String,
    val nestFoundDate: String,
    val backDateHelp: String,
    val today: String,
    val yesterday: String,
    val daysAgo: String, // "%d" placeholder
    // add-nest form
    val newMarker: String,
    val whatFound: String,
    val segNest: String,
    val segLandmark: String,
    val segTrash: String,
    val nestOrFalse: String,
    val segFalseCrawl: String,
    val photo: String,
    val retake: String,
    val cameraBtn: String,
    val gallery: String,
    val photoAdded: String,
    val location: String,
    val fromExif: String,
    val noGpsInPhoto: String,
    val confirmed: String,
    val unconfirmed: String,
    val detectedFrom: String,
    val changePlain: String,
    val noLocationYet: String,
    val notRecognizedBeach: String,
    val protection: String,
    val protNone: String,
    val protReed: String,
    val protCage: String,
    val protectionHelp: String,
    val optionalSun: String,
    val segSun: String,
    val segPartial: String,
    val segShade: String,
    val visibility: String,
    val visPublic: String,
    val visPrivate: String,
    val saveNest: String,
    val saveFalseCrawl: String,
    // stats
    val trendsTitle: String,
    val toSea: String,
    val nestsFound14: String,
    val noNestsTrend: String,
    val hatchForecast8: String,
    val hatchForecastSub: String,
    val excavationOutcomes: String,
    val excavatedWord: String,
    val hatchedEggs: String,
    val unhatchedWord: String,
    val noExcavations: String,
    // community
    val joinWhatsapp: String,
    val joinSub: String,
    val team: String,
    val youWord: String,
    val localGroupNear: String,
    val localGroup: String,
    val stubNotOnApp: String,
    val stubClaim: String,
    val weRunGroup: String,
    val reachThem: String,
    val topVolunteers: String,
    val noNestsBeFirst: String,
    val kindCommunity: String,
    val kindNgo: String,
    val kindUniversity: String,
    val kindOfficial: String,
    val roleAdmin: String,
    val roleLeader: String,
    val roleVolunteer: String,
    val reachWhatsapp: String,
    val callWord: String,
    val instagramWord: String,
    val websiteWord: String,
    val contactWord: String,
    // beach detail
    val protectedBeachBanner: String,
    val unprotectedBeachBanner: String,
    val beachLeader: String,
    val feed: String,
    val noNestsHereBeFirst: String,
    val dayWord: String,
    // air pill
    val airCleanLabel: String,
    val airModerate: String,
    val airUnhealthy: String,
    val airDustLabel: String,
    val patrolNotAdvised: String,
    val dustNotAdvised: String,
    // nest status pills + countdown + months
    val statusIncubating: String,
    val statusHatchingSoon: String,
    val statusHatched: String,
    val statusExcavated: String,
    val statusPredated: String,
    val statusWashedOver: String,
    val statusPoached: String,
    val statusLost: String,
    val statusFalseCrawl: String,
    val dayLabel: String,
    val months: List<String>,
    // onboarding (3 pages)
    val ob1Title: String,
    val ob1Body: String,
    val ob2Title: String,
    val ob2Body: String,
    val ob3Title: String,
    val ob3Body: String,
    val obNext: String,
    val obStart: String,
    val obSkip: String,
    // violations
    val segViolation: String,
    val whatViolation: String,
    val vkTent: String,
    val vkVehicle: String,
    val vkLight: String,
    val vkNoise: String,
    val vkDog: String,
    val vkLitter: String,
    val vkOther: String,
    val violationPrivateHint: String,
    val anonymousWord: String,
    val saveViolation: String,
    val filterViolations: String,
    val timelapse: String,
    val shareImpact: String,
    val shareText: String, // "%d" = hatchlings
    val addPhoto: String,
    val dupTitle: String,
    val dupBody: String, // %1 code, %2 distance
    val dupOpenExisting: String,
    val dupAddNew: String,
    // excavation screen
    val excavationTitle: String,
    val excFinalCount: String,
    val excCountWhatYouFind: String,
    val excShells: String,
    val excUnhatched: String,
    val excPipped: String,
    val excInNest: String,
    val excHelpedOut: String,
    val excSuccessLabel: String,
    val excHatchingSuccess: String,
    val excEmergenceSuccess: String,
    val excFinish: String,
    // misc hints / small labels
    val nestNotFound: String,
    val beachNotFound: String,
    val noBeachesInCity: String, // %s = city
    val openWord: String,
    val yourCommunity: String,
    val volunteersWord: String,
    val cameraFrameHint: String,
    // badge names (by code)
    val badgeFirstNest: String,
    val badgeFirstDig: String,
    val badgeRescuer: String,
    val badgeSeason50: String,
    // native iOS chrome (patrol dialog, camera permission)
    val patrolPublishTitle: String,
    val patrolKeepPrivate: String,
    val patrolPublish: String,
    val patrolPublishBody: String,
    val openSettings: String,
    // member (volunteer) profile
    val memberNestsStat: String,
    val memberHatchStat: String,
    val memberNestsSection: String,
    val memberNoNests: String,
    val memberLink: String,
)

private val EN = AppStrings(
    navMap = "Map", navBeaches = "Beaches", navLearn = "Learn", navProfile = "Profile",
    save = "Save", cancel = "Cancel", close = "Close", done = "Done", change = "Change ›",
    filterAll = "All", filterNests = "🥚 Nests", filterHatching = "● Hatching soon", filterTrash = "🧺 Trash",
    startPatrol = "● Start patrol", stopPatrol = "■ Stop patrol", noPatrolYet = "No patrol yet today",
    beaches = "Beaches", nearYou = "Near you", allBeaches = "All beaches", showBeaches = "Show beaches",
    nearMeAuto = "📍 Near me (auto)", findingBeaches = "Finding beaches near you…\nThey load automatically from the map.",
    profile = "Profile", saveAccount = "Save your account",
    saveAccountSub = "Add an email so your work isn't lost if you change phone.",
    signedIn = "Signed in", hatchlingsReached = "hatchlings reached the sea 🌊",
    dayStreak = "day streak", walked = "walked", patrols = "patrols", community = "Community",
    myBeach = "My beach", freeVolunteer = "🌊 Free volunteer", patrolClosest = "Patrol wherever's closest",
    yourHomeBeach = "Your home beach", homeBeach = "Home beach", patrolled = "Patrolled",
    badges = "Badges", noBadges = "No badges yet — patrol & log nests to earn your first 🐢",
    myPhotos = "My photos", trends = "📊  Trends & charts", language = "🌐  Language",
    yourName = "Your name", displayName = "Display name",
    signIn = "Sign in", email = "Email", passwordHint = "Password (6+ chars)",
    haveAccount = "Already have an account? Sign in", newHere = "New here? Create an account",
    saveAccountBody = "Add an email + password so your work syncs and isn't lost if you change phone.",
    welcomeBack = "Welcome back — sign in to load your nests & impact.",
    nestsWord = "nests", activeWord = "active", soonWord = "soon", hatchedWord = "hatched",
    beachWord = "Beach", protectedBeachLabel = "🛡️ Protected nesting beach", protectedWord = "protected",
    watch = "🔔 Watch", watching = "🔔 Watching", foundWord = "found", foundByWord = "Found by", hatchWindow = "Hatch window",
    predictedModel = "predicted · temperature model",
    exFullSun = "full sun", exPartial = "partial", exShade = "shade", exUnknown = "exposure ?",
    airWord = "air", rain7d = "rain 7d", timeline = "Timeline · updates & comments",
    addUpdate = "＋ Add update", comment = "💬 Comment", excavation = "⛏️ Excavation",
    excavationLockedSub = "Done by experienced volunteers & beach leaders — ask your beach leader.",
    needsConfirm = "⚠️  Needs a photo / precise location — tap to confirm",
    condition = "Condition", dateWord = "Date", whatObserved = "What did you observe?", writeComment = "Write a comment…",
    condOk = "OK", condHatching = "Hatching", condHatched = "Hatched", condDisturbed = "Disturbed",
    condPredated = "Predated", condWashed = "Washed over",
    nestFoundDate = "Nest found date",
    backDateHelp = "Word-of-mouth it was found earlier but the photo arrived now? Set the real day — up to a month back. The incubation day & hatch forecast recompute automatically.",
    today = "today", yesterday = "yesterday", daysAgo = "%d days ago",
    newMarker = "New marker", whatFound = "What did you find?",
    segNest = "🥚 Nest", segLandmark = "🚩 Landmark", segTrash = "🧺 Trash",
    nestOrFalse = "Nest or false crawl?", segFalseCrawl = "🌀 False crawl",
    photo = "Photo", retake = "📷 Retake", cameraBtn = "📷 Camera", gallery = "🖼️ Gallery", photoAdded = "Photo added",
    location = "Location", fromExif = "From photo · EXIF", noGpsInPhoto = "No GPS in photo — set to the beach",
    confirmed = "Confirmed ✓", unconfirmed = "Unconfirmed", detectedFrom = "Detected from your location",
    changePlain = "Change", noLocationYet = "No location yet — take a photo on-site or pick the beach.",
    notRecognizedBeach = "🌊 Not recognized as a known nesting beach — pick the right one.",
    protection = "Protection", protNone = "None", protReed = "🌾 Reed", protCage = "🛡️ Cage",
    protectionHelp = "Reed = stakes + reed fence + tape + sign. Cage = metal cage (stronger, but scarce & heavy).",
    optionalSun = "Optional: sun exposure", segSun = "☀️ Sun", segPartial = "⛅ Partial", segShade = "🌴 Shade",
    visibility = "Visibility", visPublic = "🌍 Public", visPrivate = "🔒 Private",
    saveNest = "Save nest 🐢", saveFalseCrawl = "Save false crawl 🌀",
    trendsTitle = "Trends", toSea = "🐢 to sea",
    nestsFound14 = "Nests found · last 14 days", noNestsTrend = "No nests logged yet — add some to see the trend.",
    hatchForecast8 = "Hatch-window forecast · next 8 weeks",
    hatchForecastSub = "When incubating nests are expected to start emerging (found date + ~incubation).",
    excavationOutcomes = "Excavation outcomes", excavatedWord = "excavated", hatchedEggs = "hatched eggs",
    unhatchedWord = "unhatched", noExcavations = "No excavations recorded yet.",
    joinWhatsapp = "💬 Join — message us on WhatsApp",
    joinSub = "New here? Message us on WhatsApp or Instagram — an admin will add you to the team.",
    team = "Team", youWord = "you", localGroupNear = "Local group · near", localGroup = "Local conservation group",
    stubNotOnApp = "🐢 This local group isn't on Caretta Friends yet — reach out to them directly below. ",
    stubClaim = "Are you part of it? Message us and we'll give your admins access.",
    weRunGroup = "🙋 We run this group — give us access", reachThem = "Reach them",
    topVolunteers = "Top volunteers · by nests", noNestsBeFirst = "No nests logged yet — be the first to mark one this season 🥚",
    kindCommunity = "🐢 Volunteer group", kindNgo = "🌍 NGO", kindUniversity = "🎓 University", kindOfficial = "🏛️ Official",
    roleAdmin = "Admin", roleLeader = "Leader", roleVolunteer = "Volunteer",
    reachWhatsapp = "Message on WhatsApp", callWord = "Call", instagramWord = "Instagram", websiteWord = "Website", contactWord = "Contact",
    protectedBeachBanner = "🛡️ Official protected nesting beach — night access banned in season.",
    unprotectedBeachBanner = "🏖️ Not an official protected beach — nests logged here still count & sync.",
    beachLeader = "beach leader", feed = "Feed", noNestsHereBeFirst = "No nests logged here yet — be the first 🥚",
    dayWord = "Day",
    airCleanLabel = "Air clean", airModerate = "Moderate air", airUnhealthy = "Unhealthy", airDustLabel = "Dust",
    patrolNotAdvised = "patrol not advised", dustNotAdvised = "⚠ Dust — patrol not advised",
    statusIncubating = "Incubating", statusHatchingSoon = "Hatching soon", statusHatched = "Hatched",
    statusExcavated = "Excavated", statusPredated = "Predated", statusWashedOver = "Washed over",
    statusPoached = "Poached", statusLost = "Lost", statusFalseCrawl = "False crawl", dayLabel = "DAY",
    months = listOf("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"),
    ob1Title = "Welcome to Caretta Friends 🐢",
    ob1Body = "We protect loggerhead sea-turtle nests together — one beach, one nest, one hatchling at a time.",
    ob2Title = "Found a nest? Add it 📍",
    ob2Body = "Snap a photo on the beach and mark the nest. Then patrol, log updates, and watch the hatch forecast until the hatchlings reach the sea.",
    ob3Title = "Every patrol counts 🙌",
    ob3Body = "Join your local community, keep the beach dark at night, and help hundreds of hatchlings make it to the waves. Ready?",
    obNext = "Next", obStart = "Let's go 🌊", obSkip = "Skip",
    segViolation = "⛔ Violation", whatViolation = "What's the violation?",
    vkTent = "⛺ Tent", vkVehicle = "🚗 Vehicle", vkLight = "🔦 Light", vkNoise = "🔊 Noise",
    vkDog = "🐕 Dog", vkLitter = "🧺 Litter", vkOther = "⚠ Other",
    violationPrivateHint = "Kept private for the record — guests won't see who reported it.",
    anonymousWord = "Report anonymously", saveViolation = "Report violation ⛔",
    filterViolations = "⛔ Violations", timelapse = "🎞️ Timelapse",
    shareImpact = "📣 Share my impact",
    shareText = "🐢 I'm a Caretta Friends volunteer — %d hatchlings have reached the sea! Join us: carettafriends.com",
    addPhoto = "📷 Photo",
    dupTitle = "Already logged here?",
    dupBody = "%1\$s is already marked %2\$s away. Open it instead of adding a duplicate?",
    dupOpenExisting = "Open %1\$s",
    dupAddNew = "No, add a new nest",
    excavationTitle = "Nest excavation",
    excFinalCount = "final count",
    excCountWhatYouFind = "Count what you find",
    excShells = "Hatched / empty shells",
    excUnhatched = "Unhatched / whole eggs",
    excPipped = "Pipped / in egg",
    excInNest = "In nest / stuck",
    excHelpedOut = "Helped out / rescued",
    excSuccessLabel = "Success",
    excHatchingSuccess = "Hatching success",
    excEmergenceSuccess = "Emergence success",
    excFinish = "Finish & celebrate 🎉",
    nestNotFound = "Nest not found",
    beachNotFound = "Beach not found",
    noBeachesInCity = "No beaches in %s yet.",
    openWord = "Open",
    yourCommunity = "Your community",
    volunteersWord = "volunteers",
    cameraFrameHint = "Frame the nest",
    badgeFirstNest = "First nest",
    badgeFirstDig = "First excavation",
    badgeRescuer = "Rescuer",
    badgeSeason50 = "Season 50",
    patrolPublishTitle = "Publish this patrol?",
    patrolKeepPrivate = "Keep private",
    patrolPublish = "Publish",
    patrolPublishBody = "Your walk is saved on your phone. Publish to share the route with your community — your live location is never shared.",
    openSettings = "Open Settings",
    memberNestsStat = "nests found",
    memberHatchStat = "hatchlings freed",
    memberNestsSection = "Nests",
    memberNoNests = "No nests logged yet.",
    memberLink = "Link",
)

private val RU = AppStrings(
    navMap = "Карта", navBeaches = "Пляжи", navLearn = "Гайд", navProfile = "Профиль",
    save = "Сохранить", cancel = "Отмена", close = "Закрыть", done = "Готово", change = "Изменить ›",
    filterAll = "Все", filterNests = "🥚 Гнёзда", filterHatching = "● Скоро вылупятся", filterTrash = "🧺 Мусор",
    startPatrol = "● Начать патруль", stopPatrol = "■ Стоп патруль", noPatrolYet = "Патруля сегодня ещё нет",
    beaches = "Пляжи", nearYou = "Рядом с вами", allBeaches = "Все пляжи", showBeaches = "Показывать пляжи",
    nearMeAuto = "📍 Рядом (авто)", findingBeaches = "Ищем пляжи рядом…\nОни подгружаются с карты автоматически.",
    profile = "Профиль", saveAccount = "Сохранить аккаунт",
    saveAccountSub = "Добавь почту, чтобы данные не потерялись при смене телефона.",
    signedIn = "Вы вошли", hatchlingsReached = "черепашат добрались до моря 🌊",
    dayStreak = "дней подряд", walked = "пройдено", patrols = "патрулей", community = "Сообщество",
    myBeach = "Мой пляж", freeVolunteer = "🌊 Свободный волонтёр", patrolClosest = "Патрулирую где ближе",
    yourHomeBeach = "Твой домашний пляж", homeBeach = "Домашний пляж", patrolled = "Был на пляжах",
    badges = "Бейджи", noBadges = "Бейджей пока нет — патрулируй и отмечай гнёзда 🐢",
    myPhotos = "Мои фото", trends = "📊  Графики и тренды", language = "🌐  Язык",
    yourName = "Твоё имя", displayName = "Отображаемое имя",
    signIn = "Войти", email = "Почта", passwordHint = "Пароль (6+ символов)",
    haveAccount = "Уже есть аккаунт? Войти", newHere = "Впервые? Создать аккаунт",
    saveAccountBody = "Добавь почту и пароль — данные синхронизируются и не потеряются при смене телефона.",
    welcomeBack = "С возвращением — войди, чтобы загрузить свои гнёзда и вклад.",
    nestsWord = "гнёзд", activeWord = "активн.", soonWord = "скоро", hatchedWord = "вылупились",
    beachWord = "Пляж", protectedBeachLabel = "🛡️ Охраняемый пляж гнездования", protectedWord = "под охраной",
    watch = "🔔 Следить", watching = "🔔 Слежу", foundWord = "найдено", foundByWord = "Автор находки", hatchWindow = "Окно вылупления",
    predictedModel = "прогноз · температурная модель",
    exFullSun = "солнце", exPartial = "полутень", exShade = "тень", exUnknown = "освещённость ?",
    airWord = "возд.", rain7d = "дождь 7д", timeline = "Лента · апдейты и комменты",
    addUpdate = "＋ Апдейт", comment = "💬 Коммент", excavation = "⛏️ Вскрытие",
    excavationLockedSub = "Делают опытные волонтёры и лидеры пляжа — спроси своего лидера.",
    needsConfirm = "⚠️  Нужно фото / точная точка — нажми, чтобы подтвердить",
    condition = "Состояние", dateWord = "Дата", whatObserved = "Что заметил?", writeComment = "Напиши комментарий…",
    condOk = "ОК", condHatching = "Вылупляются", condHatched = "Вылупились", condDisturbed = "Потревожено",
    condPredated = "Хищник", condWashed = "Смыло",
    nestFoundDate = "Дата находки гнезда",
    backDateHelp = "Со слов нашли раньше, а фото дошло сейчас? Поставь реальный день — до месяца назад. День инкубации и прогноз вылупления пересчитаются автоматически.",
    today = "сегодня", yesterday = "вчера", daysAgo = "%d дн. назад",
    newMarker = "Новая метка", whatFound = "Что ты нашёл?",
    segNest = "🥚 Гнездо", segLandmark = "🚩 Ориентир", segTrash = "🧺 Мусор",
    nestOrFalse = "Гнездо или ложный выход?", segFalseCrawl = "🌀 Ложный выход",
    photo = "Фото", retake = "📷 Переснять", cameraBtn = "📷 Камера", gallery = "🖼️ Галерея", photoAdded = "Фото добавлено",
    location = "Локация", fromExif = "Из фото · EXIF", noGpsInPhoto = "В фото нет GPS — привязано к пляжу",
    confirmed = "Подтверждено ✓", unconfirmed = "Не подтверждено", detectedFrom = "Определено по локации",
    changePlain = "Изменить", noLocationYet = "Локации пока нет — сделай фото на месте или выбери пляж.",
    notRecognizedBeach = "🌊 Не распознан как известный пляж — выбери нужный.",
    protection = "Защита", protNone = "Нет", protReed = "🌾 Тростник", protCage = "🛡️ Клетка",
    protectionHelp = "Тростник = колышки + тростниковый забор + лента + табличка. Клетка = металлическая (крепче, но редкая и тяжёлая).",
    optionalSun = "Опционально: освещённость", segSun = "☀️ Солнце", segPartial = "⛅ Полутень", segShade = "🌴 Тень",
    visibility = "Видимость", visPublic = "🌍 Публично", visPrivate = "🔒 Приватно",
    saveNest = "Сохранить гнездо 🐢", saveFalseCrawl = "Сохранить ложный выход 🌀",
    trendsTitle = "Тренды", toSea = "🐢 в море",
    nestsFound14 = "Найдено гнёзд · за 14 дней", noNestsTrend = "Гнёзд пока нет — добавь, чтобы увидеть тренд.",
    hatchForecast8 = "Прогноз вылупления · след. 8 недель",
    hatchForecastSub = "Когда инкубируемые гнёзда должны начать вылупляться (дата находки + ~инкубация).",
    excavationOutcomes = "Итоги вскрытий", excavatedWord = "вскрыто", hatchedEggs = "вылупилось",
    unhatchedWord = "не вылупилось", noExcavations = "Вскрытий пока нет.",
    joinWhatsapp = "💬 Присоединиться — напиши нам в WhatsApp",
    joinSub = "Впервые? Напиши в WhatsApp или Instagram — админ добавит тебя в команду.",
    team = "Команда", youWord = "ты", localGroupNear = "Локальная группа · рядом с", localGroup = "Локальная природоохранная группа",
    stubNotOnApp = "🐢 Этой группы пока нет в Caretta Friends — свяжись с ними напрямую ниже. ",
    stubClaim = "Ты из этой группы? Напиши нам, дадим доступ вашим админам.",
    weRunGroup = "🙋 Это наша группа — дайте нам доступ", reachThem = "Связаться",
    topVolunteers = "Топ волонтёров · по гнёздам", noNestsBeFirst = "Гнёзд пока нет — отметь первое в этом сезоне 🥚",
    kindCommunity = "🐢 Группа волонтёров", kindNgo = "🌍 НКО", kindUniversity = "🎓 Университет", kindOfficial = "🏛️ Официальный орган",
    roleAdmin = "Админ", roleLeader = "Лидер", roleVolunteer = "Волонтёр",
    reachWhatsapp = "Написать в WhatsApp", callWord = "Позвонить", instagramWord = "Instagram", websiteWord = "Сайт", contactWord = "Контакт",
    protectedBeachBanner = "🛡️ Официально охраняемый пляж — ночью в сезон вход запрещён.",
    unprotectedBeachBanner = "🏖️ Неофициальный пляж — гнёзда здесь всё равно считаются и синхронизируются.",
    beachLeader = "лидер пляжа", feed = "Лента", noNestsHereBeFirst = "Здесь гнёзд пока нет — будь первым 🥚",
    dayWord = "День",
    airCleanLabel = "Воздух чистый", airModerate = "Умеренный воздух", airUnhealthy = "Вредный", airDustLabel = "Пыль",
    patrolNotAdvised = "патруль не рекомендуется", dustNotAdvised = "⚠ Пыль — патруль не рекомендуется",
    statusIncubating = "Инкубация", statusHatchingSoon = "Скоро вылупление", statusHatched = "Вылупилось",
    statusExcavated = "Вскрыто", statusPredated = "Хищник", statusWashedOver = "Смыло",
    statusPoached = "Разорено", statusLost = "Потеряно", statusFalseCrawl = "Ложный выход", dayLabel = "ДЕНЬ",
    months = listOf("янв","фев","мар","апр","май","июн","июл","авг","сен","окт","ноя","дек"),
    ob1Title = "Добро пожаловать в Caretta Friends 🐢",
    ob1Body = "Мы вместе защищаем гнёзда морских черепах-логгерхедов — по одному пляжу, гнезду и черепашонку.",
    ob2Title = "Нашёл гнездо? Добавь 📍",
    ob2Body = "Сделай фото на пляже и отметь гнездо. Потом патрулируй, добавляй апдейты и следи за прогнозом вылупления, пока черепашата не доберутся до моря.",
    ob3Title = "Каждый патруль важен 🙌",
    ob3Body = "Присоединяйся к местному сообществу, держи пляж тёмным ночью и помоги сотням черепашат добраться до волн. Готов?",
    obNext = "Далее", obStart = "Поехали 🌊", obSkip = "Пропустить",
    segViolation = "⛔ Нарушение", whatViolation = "Что за нарушение?",
    vkTent = "⛺ Палатка", vkVehicle = "🚗 Машина", vkLight = "🔦 Свет", vkNoise = "🔊 Шум",
    vkDog = "🐕 Собака", vkLitter = "🧺 Мусор", vkOther = "⚠ Другое",
    violationPrivateHint = "Хранится приватно для жалобы — гости не увидят, кто сообщил.",
    anonymousWord = "Сообщить анонимно", saveViolation = "Сообщить о нарушении ⛔",
    filterViolations = "⛔ Нарушения", timelapse = "🎞️ Таймлапс",
    shareImpact = "📣 Поделиться вкладом",
    shareText = "🐢 Я волонтёр Caretta Friends — %d черепашат добрались до моря! Присоединяйся: carettafriends.com",
    addPhoto = "📷 Фото",
    dupTitle = "Уже отмечено здесь?",
    dupBody = "%1\$s уже отмечено в %2\$s отсюда. Открыть его, а не создавать дубль?",
    dupOpenExisting = "Открыть %1\$s",
    dupAddNew = "Нет, это новое гнездо",
    excavationTitle = "Вскрытие гнезда",
    excFinalCount = "финальный подсчёт",
    excCountWhatYouFind = "Считай, что нашёл",
    excShells = "Вылупились / пустые скорлупки",
    excUnhatched = "Не вылупились / целые яйца",
    excPipped = "Проклюнулись / в яйце",
    excInNest = "В гнезде / застряли",
    excHelpedOut = "Помогли выбраться / спасли",
    excSuccessLabel = "Успех",
    excHatchingSuccess = "Успех вылупления",
    excEmergenceSuccess = "Успех выхода",
    excFinish = "Готово, отмечаем 🎉",
    nestNotFound = "Гнездо не найдено",
    beachNotFound = "Пляж не найден",
    noBeachesInCity = "Пляжей в %s пока нет.",
    openWord = "Открыть",
    yourCommunity = "Твоё сообщество",
    volunteersWord = "волонтёров",
    cameraFrameHint = "Наведи на гнездо",
    badgeFirstNest = "Первое гнездо",
    badgeFirstDig = "Первое вскрытие",
    badgeRescuer = "Спасатель",
    badgeSeason50 = "Сезон 50",
    patrolPublishTitle = "Опубликовать патруль?",
    patrolKeepPrivate = "Оставить приватным",
    patrolPublish = "Опубликовать",
    patrolPublishBody = "Прогулка сохранена на телефоне. Опубликуй, чтобы поделиться маршрутом с сообществом — твоя геопозиция в реальном времени никогда не передаётся.",
    openSettings = "Открыть настройки",
    memberNestsStat = "гнёзд найдено",
    memberHatchStat = "черепашат спасено",
    memberNestsSection = "Гнёзда",
    memberNoNests = "Пока нет гнёзд.",
    memberLink = "Ссылка",
)

private val TR = AppStrings(
    navMap = "Harita", navBeaches = "Plajlar", navLearn = "Rehber", navProfile = "Profil",
    save = "Kaydet", cancel = "İptal", close = "Kapat", done = "Tamam", change = "Değiştir ›",
    filterAll = "Hepsi", filterNests = "🥚 Yuvalar", filterHatching = "● Yakında çıkacak", filterTrash = "🧺 Çöp",
    startPatrol = "● Devriyeye başla", stopPatrol = "■ Devriyeyi bitir", noPatrolYet = "Bugün henüz devriye yok",
    beaches = "Plajlar", nearYou = "Yakınında", allBeaches = "Tüm plajlar", showBeaches = "Plajları göster",
    nearMeAuto = "📍 Yakınım (oto)", findingBeaches = "Yakındaki plajlar aranıyor…\nHaritadan otomatik yüklenir.",
    profile = "Profil", saveAccount = "Hesabını kaydet",
    saveAccountSub = "Telefon değişince kaybolmaması için bir e-posta ekle.",
    signedIn = "Giriş yapıldı", hatchlingsReached = "yavru denize ulaştı 🌊",
    dayStreak = "gün seri", walked = "yürüdün", patrols = "devriye", community = "Topluluk",
    myBeach = "Plajım", freeVolunteer = "🌊 Serbest gönüllü", patrolClosest = "En yakın neresiyse orada",
    yourHomeBeach = "Ana plajın", homeBeach = "Ana plaj", patrolled = "Gezdiğin plajlar",
    badges = "Rozetler", noBadges = "Henüz rozet yok — devriye gez ve yuva kaydet 🐢",
    myPhotos = "Fotoğraflarım", trends = "📊  Grafikler ve eğilimler", language = "🌐  Dil",
    yourName = "Adın", displayName = "Görünen ad",
    signIn = "Giriş yap", email = "E-posta", passwordHint = "Şifre (6+ karakter)",
    haveAccount = "Hesabın var mı? Giriş yap", newHere = "Yeni misin? Hesap oluştur",
    saveAccountBody = "E-posta + şifre ekle — verilerin senkronize olur, telefon değişince kaybolmaz.",
    welcomeBack = "Tekrar hoş geldin — yuvalarını ve katkını yüklemek için giriş yap.",
    nestsWord = "yuva", activeWord = "aktif", soonWord = "yakında", hatchedWord = "çıktı",
    beachWord = "Plaj", protectedBeachLabel = "🛡️ Korunan yuvalama plajı", protectedWord = "korunan",
    watch = "🔔 Takip et", watching = "🔔 Takipte", foundWord = "bulundu", foundByWord = "Bulan", hatchWindow = "Çıkış aralığı",
    predictedModel = "tahmin · sıcaklık modeli",
    exFullSun = "tam güneş", exPartial = "yarı gölge", exShade = "gölge", exUnknown = "ışık ?",
    airWord = "hava", rain7d = "yağmur 7g", timeline = "Zaman çizelgesi · güncelleme & yorum",
    addUpdate = "＋ Güncelle", comment = "💬 Yorum", excavation = "⛏️ Kazı",
    excavationLockedSub = "Deneyimli gönüllüler ve plaj liderleri yapar — liderine sor.",
    needsConfirm = "⚠️  Fotoğraf / kesin konum gerekli — onaylamak için dokun",
    condition = "Durum", dateWord = "Tarih", whatObserved = "Ne gözlemledin?", writeComment = "Bir yorum yaz…",
    condOk = "OK", condHatching = "Çıkıyor", condHatched = "Çıktı", condDisturbed = "Rahatsız",
    condPredated = "Avlanmış", condWashed = "Su bastı",
    nestFoundDate = "Yuva buluş tarihi",
    backDateHelp = "Söylentiye göre daha önce bulundu ama fotoğraf şimdi mi geldi? Gerçek günü ayarla — bir aya kadar. İnkübasyon günü ve çıkış tahmini otomatik güncellenir.",
    today = "bugün", yesterday = "dün", daysAgo = "%d gün önce",
    newMarker = "Yeni işaret", whatFound = "Ne buldun?",
    segNest = "🥚 Yuva", segLandmark = "🚩 Nirengi", segTrash = "🧺 Çöp",
    nestOrFalse = "Yuva mı, boş çıkış mı?", segFalseCrawl = "🌀 Boş çıkış",
    photo = "Fotoğraf", retake = "📷 Tekrar çek", cameraBtn = "📷 Kamera", gallery = "🖼️ Galeri", photoAdded = "Fotoğraf eklendi",
    location = "Konum", fromExif = "Fotoğraftan · EXIF", noGpsInPhoto = "Fotoğrafta GPS yok — plaja bağlandı",
    confirmed = "Onaylandı ✓", unconfirmed = "Onaysız", detectedFrom = "Konumundan algılandı",
    changePlain = "Değiştir", noLocationYet = "Henüz konum yok — yerinde fotoğraf çek ya da plaj seç.",
    notRecognizedBeach = "🌊 Bilinen bir yuvalama plajı değil — doğrusunu seç.",
    protection = "Koruma", protNone = "Yok", protReed = "🌾 Kamış", protCage = "🛡️ Kafes",
    protectionHelp = "Kamış = kazık + kamış çit + bant + tabela. Kafes = metal kafes (daha güçlü ama nadir ve ağır).",
    optionalSun = "İsteğe bağlı: güneş", segSun = "☀️ Güneş", segPartial = "⛅ Yarı", segShade = "🌴 Gölge",
    visibility = "Görünürlük", visPublic = "🌍 Herkese açık", visPrivate = "🔒 Özel",
    saveNest = "Yuvayı kaydet 🐢", saveFalseCrawl = "Boş çıkışı kaydet 🌀",
    trendsTitle = "Eğilimler", toSea = "🐢 denize",
    nestsFound14 = "Bulunan yuva · son 14 gün", noNestsTrend = "Henüz yuva yok — eğilimi görmek için ekle.",
    hatchForecast8 = "Çıkış tahmini · önümüzdeki 8 hafta",
    hatchForecastSub = "İnkübe olan yuvaların ne zaman çıkmaya başlayacağı (buluş tarihi + ~inkübasyon).",
    excavationOutcomes = "Kazı sonuçları", excavatedWord = "kazıldı", hatchedEggs = "çıkan",
    unhatchedWord = "çıkmayan", noExcavations = "Henüz kazı yok.",
    joinWhatsapp = "💬 Katıl — bize WhatsApp'tan yaz",
    joinSub = "Yeni misin? WhatsApp veya Instagram'dan yaz — bir yönetici seni ekibe ekler.",
    team = "Ekip", youWord = "sen", localGroupNear = "Yerel grup · yakın", localGroup = "Yerel koruma grubu",
    stubNotOnApp = "🐢 Bu grup henüz Caretta Friends'te değil — aşağıdan doğrudan ulaş. ",
    stubClaim = "Bu grubun parçası mısın? Bize yaz, yöneticilerine erişim verelim.",
    weRunGroup = "🙋 Bu grubu biz yönetiyoruz — bize erişim verin", reachThem = "Ulaş",
    topVolunteers = "En iyi gönüllüler · yuvaya göre", noNestsBeFirst = "Henüz yuva yok — bu sezon ilk işareti sen koy 🥚",
    kindCommunity = "🐢 Gönüllü grubu", kindNgo = "🌍 STK", kindUniversity = "🎓 Üniversite", kindOfficial = "🏛️ Resmî",
    roleAdmin = "Yönetici", roleLeader = "Lider", roleVolunteer = "Gönüllü",
    reachWhatsapp = "WhatsApp'tan yaz", callWord = "Ara", instagramWord = "Instagram", websiteWord = "Web sitesi", contactWord = "İletişim",
    protectedBeachBanner = "🛡️ Resmî korunan yuvalama plajı — sezonda gece girişi yasak.",
    unprotectedBeachBanner = "🏖️ Resmî korunan plaj değil — buradaki yuvalar yine de sayılır ve senkronize olur.",
    beachLeader = "plaj lideri", feed = "Akış", noNestsHereBeFirst = "Burada henüz yuva yok — ilk sen ol 🥚",
    dayWord = "Gün",
    airCleanLabel = "Hava temiz", airModerate = "Orta hava", airUnhealthy = "Sağlıksız", airDustLabel = "Toz",
    patrolNotAdvised = "devriye önerilmez", dustNotAdvised = "⚠ Toz — devriye önerilmez",
    statusIncubating = "İnkübasyon", statusHatchingSoon = "Yakında çıkış", statusHatched = "Çıktı",
    statusExcavated = "Kazıldı", statusPredated = "Avlandı", statusWashedOver = "Su bastı",
    statusPoached = "Yağmalandı", statusLost = "Kayıp", statusFalseCrawl = "Boş çıkış", dayLabel = "GÜN",
    months = listOf("Oca","Şub","Mar","Nis","May","Haz","Tem","Ağu","Eyl","Eki","Kas","Ara"),
    ob1Title = "Caretta Friends'e hoş geldin 🐢",
    ob1Body = "Deniz kaplumbağası (caretta) yuvalarını birlikte koruyoruz — her plaj, her yuva, her yavru için.",
    ob2Title = "Yuva mı buldun? Ekle 📍",
    ob2Body = "Plajda bir fotoğraf çek ve yuvayı işaretle. Sonra devriye gez, güncelleme ekle ve yavrular denize ulaşana kadar çıkış tahminini izle.",
    ob3Title = "Her devriye önemli 🙌",
    ob3Body = "Yerel topluluğuna katıl, geceleri plajı karanlık tut ve yüzlerce yavrunun dalgalara ulaşmasına yardım et. Hazır mısın?",
    obNext = "İleri", obStart = "Hadi başlayalım 🌊", obSkip = "Atla",
    segViolation = "⛔ İhlal", whatViolation = "İhlal nedir?",
    vkTent = "⛺ Çadır", vkVehicle = "🚗 Araç", vkLight = "🔦 Işık", vkNoise = "🔊 Gürültü",
    vkDog = "🐕 Köpek", vkLitter = "🧺 Çöp", vkOther = "⚠ Diğer",
    violationPrivateHint = "Kayıt için gizli tutulur — misafirler kimin bildirdiğini görmez.",
    anonymousWord = "Anonim bildir", saveViolation = "İhlal bildir ⛔",
    filterViolations = "⛔ İhlaller", timelapse = "🎞️ Zaman akışı",
    shareImpact = "📣 Katkımı paylaş",
    shareText = "🐢 Ben bir Caretta Friends gönüllüsüyüm — %d yavru denize ulaştı! Sen de katıl: carettafriends.com",
    addPhoto = "📷 Fotoğraf",
    dupTitle = "Burada zaten var mı?",
    dupBody = "%1\$s zaten %2\$s ötede işaretli. Kopya eklemek yerine onu aç?",
    dupOpenExisting = "%1\$s'i aç",
    dupAddNew = "Hayır, yeni yuva",
    excavationTitle = "Yuva kazısı",
    excFinalCount = "son sayım",
    excCountWhatYouFind = "Bulduklarını say",
    excShells = "Çıkmış / boş kabuk",
    excUnhatched = "Çıkmamış / bütün yumurta",
    excPipped = "Gagalamış / yumurtada",
    excInNest = "Yuvada / sıkışmış",
    excHelpedOut = "Kurtarıldı / çıkarıldı",
    excSuccessLabel = "Başarı",
    excHatchingSuccess = "Çıkış başarısı",
    excEmergenceSuccess = "Yüzeye çıkış başarısı",
    excFinish = "Bitir & kutla 🎉",
    nestNotFound = "Yuva bulunamadı",
    beachNotFound = "Plaj bulunamadı",
    noBeachesInCity = "%s'de henüz plaj yok.",
    openWord = "Aç",
    yourCommunity = "Topluluğun",
    volunteersWord = "gönüllü",
    cameraFrameHint = "Yuvayı çerçevele",
    badgeFirstNest = "İlk yuva",
    badgeFirstDig = "İlk kazı",
    badgeRescuer = "Kurtarıcı",
    badgeSeason50 = "Sezon 50",
    patrolPublishTitle = "Bu devriyeyi yayınla?",
    patrolKeepPrivate = "Özel tut",
    patrolPublish = "Yayınla",
    patrolPublishBody = "Yürüyüşün telefonunda kaydedildi. Rotayı toplulukla paylaşmak için yayınla — canlı konumun asla paylaşılmaz.",
    openSettings = "Ayarları aç",
    memberNestsStat = "yuva bulundu",
    memberHatchStat = "yavru kurtarıldı",
    memberNestsSection = "Yuvalar",
    memberNoNests = "Henüz yuva yok.",
    memberLink = "Bağlantı",
)

/** The string bundle for [lang] ("ru" / "tr" / anything else → EN). */
fun appStrings(lang: String): AppStrings = when (lang.lowercase()) {
    "ru" -> RU
    "tr" -> TR
    else -> EN
}

/** Localized display name for a badge by its stable [code]; unknown codes fall back to the code.
 *  Lives next to the string bundles so a new badge only needs its fields + one branch here. */
fun AppStrings.badgeName(code: String): String = when (code) {
    "first_nest" -> badgeFirstNest
    "first_dig" -> badgeFirstDig
    "rescuer" -> badgeRescuer
    "season50" -> badgeSeason50
    else -> code
}
